// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/wuyan94zl/go-zero-blog/app/users/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: UsersHandler(serverCtx),
			},
		},
	)
}
