// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	Code      int    `json:"code"`
	Data      string `json:"data"`
	Message   string `json:"message"`
	RequestId string `json:"request_id"`
}

type UserListRequest struct {
	Name string `json:"name"`
}
