// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/wuyan94zl/go-zero-blog/app/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/add",
				Handler: UserAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/info",
				Handler: UserInfoHandler(serverCtx),
			},
		},
	)
}
